---

- name: ensure supervisord is running
  service: name=supervisor
           state=started

- name: generate config for uswgi process
  template: src=supervisor.conf
            dest=/etc/supervisor/conf.d/{{ django_project }}.conf
            mode=0644
            owner=root
            group=root
  register: supervisor

- name: reload supervisord
  command: supervisorctl update
  when: supervisor.changed
